# Generated by Django 3.2.3 on 2021-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=5.0)),
                ('pumpSpeed', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW'), ('OFF', 'OFF')], default='OFF', max_length=20)),
                ('light', models.BooleanField(default=False)),
            ],
        ),
    ]
